
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALL ATUALIZAR COLECAO CRIAR DATABASE DELETAR ID INSERIR LER QUERY TABELA_DE_EXEMPLO VALORsql : CRIAR DATABASE VALOR\n            | CRIAR TABELA_DE_EXEMPLO\n            | INSERIR VALOR\n            | LER COLECAO VALOR\n            | LER COLECAO ID VALOR\n            | LER COLECAO QUERY VALOR\n            | ATUALIZAR COLECAO ID VALOR\n            | ATUALIZAR COLECAO QUERY VALOR\n            | DELETAR COLECAO VALOR\n            | DELETAR COLECAO ID VALOR\n            | DELETAR COLECAO QUERY VALOR\n            '
    
_lr_action_items = {'CRIAR':([0,],[2,]),'INSERIR':([0,],[3,]),'LER':([0,],[4,]),'ATUALIZAR':([0,],[5,]),'DELETAR':([0,],[6,]),'$end':([1,8,9,13,14,19,22,23,24,25,26,27,],[0,-2,-3,-1,-4,-9,-5,-6,-7,-8,-10,-11,]),'DATABASE':([2,],[7,]),'TABELA_DE_EXEMPLO':([2,],[8,]),'VALOR':([3,7,10,12,15,16,17,18,20,21,],[9,13,14,19,22,23,24,25,26,27,]),'COLECAO':([4,5,6,],[10,11,12,]),'ID':([10,11,12,],[15,17,20,]),'QUERY':([10,11,12,],[16,18,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sql':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sql","S'",1,None,None,None),
  ('sql -> CRIAR DATABASE VALOR','sql',3,'p_crud','calculator.py',60),
  ('sql -> CRIAR TABELA_DE_EXEMPLO','sql',2,'p_crud','calculator.py',61),
  ('sql -> INSERIR VALOR','sql',2,'p_crud','calculator.py',62),
  ('sql -> LER COLECAO VALOR','sql',3,'p_crud','calculator.py',63),
  ('sql -> LER COLECAO ID VALOR','sql',4,'p_crud','calculator.py',64),
  ('sql -> LER COLECAO QUERY VALOR','sql',4,'p_crud','calculator.py',65),
  ('sql -> ATUALIZAR COLECAO ID VALOR','sql',4,'p_crud','calculator.py',66),
  ('sql -> ATUALIZAR COLECAO QUERY VALOR','sql',4,'p_crud','calculator.py',67),
  ('sql -> DELETAR COLECAO VALOR','sql',3,'p_crud','calculator.py',68),
  ('sql -> DELETAR COLECAO ID VALOR','sql',4,'p_crud','calculator.py',69),
  ('sql -> DELETAR COLECAO QUERY VALOR','sql',4,'p_crud','calculator.py',70),
]
